pagehelper:
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
  helper-dialect: mysql

spring:
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 20000
    password:
    jedis:
      pool:
        max-idle: 8
        max-wait:
        min-idle: 0

  datasource:
    url: jdbc:mysql://47.96.159.71/oomall?useUnicode=true&characterEncoding=utf8&useSSL=true&serverTimezone=GMT%2B8
    username: oomall
    password: oomallp@$$w0rd
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  type-aliases-package: com.tardybird.goodsinfo.domain
  mapper-locations: classpath:mapper/*.xml

server:
  port: 8080
  address: 0.0.0.0

goods:
  #redis缓存失效时间，单位分钟
  redisExpireTime: 1
  #预提库存数量
  preDeductQuantity: 3