spring:
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 20000
    #    集群环境打开下面注释，单机不需要打开
    #    cluster:
    #      集群信息
    #      nodes: xxx.xxx.xxx.xxx:xxxx,xxx.xxx.xxx.xxx:xxxx,xxx.xxx.xxx.xxx:xxxx
    #      #默认值是5 一般当此值设置过大时，容易报：Too many Cluster redirections
    #      maxRedirects: 3
    pool:

      max-active: 8
      min-idle: 0
      max-idle: 8
      max-wait: -1
    password:

  datasource:
    url: jdbc:mysql://47.96.159.71/oomall?useUnicode=true&characterEncoding=utf8&useSSL=true&serverTimezone=GMT%2B8
    username: oomall
    password: oomallp@$$w0rd
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  type-aliases-package: com.tardybird.goodsinfo.domain
  mapper-locations: classpath:mapper/*.xml

server:
  port: 8080
  address: 0.0.0.0

GoodsInfo:
  #redis缓存失效时间，单位分钟
  redisExpireTime: 1
  #预提库存数量
  preDeductQty: 3