pagehelper:
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
  helper-dialect: mysql

spring:
  redis:
    host: 47.96.159.71
    port: 6379
    timeout: 20000
    password:
    jedis:
      pool:
        max-idle: 8
        max-wait:
        min-idle: 0
  datasource:
    url: jdbc:mysql://47.96.159.71/oomall?useUnicode=true&characterEncoding=utf8&useSSL=true&serverTimezone=GMT%2B8
    username: oomall
    password: oomallp@$$w0rd
    #  datasource:
    #    url: jdbc:mysql://148.70.28.112/wowomall?useUnicode=true&characterEncoding=utf8&useSSL=false
    #    username: wowoto
    #    password: zqhlovekly
    driver-class-name: com.mysql.cj.jdbc.Driver

  application:
    name: goodsinfo

mybatis:
  type-aliases-package: com.tardybird.goodsinfo.po
  mapper-locations: classpath:mapper/*.xml

server:
  port: 8800
  address: 0.0.0.0

eureka:
  client:
    service-url:
      defaultZone: http://148.70.28.112:8761/eureka/
  instance:
    prefer-ip-address: true
    ip-address: 47.96.159.71
    non-secure-port: 8800
#    ip-address: localhost

goods:
  #redis缓存失效时间，单位分钟
  redisExpireTime: 1
  #预提库存数量
  preDeductQuantity: 3